### ISSUE TITLE
Переопределение hashCode 

### ISSUE THREAD

**Issue by polyak01** [Wadimir/SamsungJava#2]
Для более точного переопределения hashCode нужно задействовать все переменные:
https://github.com/Wadimir/SamsungJava/blob/New_Figure/src/Figur/Parallelogram.java#L38 
иначе hashCode у двух объектов может совпадать, при том, что высота может быть разная. 

Тоже касается equals в некоторых классах.

**Comment by Wadimir** [comment]
Fixed hashCode and equals.
